### PR TITLE
run bubble graph updater in a continuous interval

### LINKED ISSUE #316: broken arrows in bubble graph
bubble graph sometimes have it's arrows broken, especially after a few refreshes:

Screen Shot 2022-03-20 at 19 38 11

### PR DESCRIPTION
**Pull request by KutnerUri**
closed #316 
this will ensure the bubble graph are correctly positioned - by applying them inside a set interval

### CODE REVIEW

File: community/ui/graph/edge/auto-reloader.tsx [hunk 1]
```diff
@@ -1,28 +1,37 @@
...
       {children}
-      <ReloadArrows />
+      <ReloadArrows delay={delay} interval={interval} />
     </Xwrapper>
   );
 }
 
 // this will be fixed in react-xarrows v3.0.0
-function ReloadArrows() {
+function ReloadArrows({ delay = 1000, interval = false }: ReloadOptions) {
```
Comment (odedre) [inline community/ui/graph/edge/auto-reloader.tsx:21]: this is basically the same as the hack fix we previously had. we should fix properly

**Review by odedre — APPROVED** [review]
