### PR TITLE
fix master errors

### LINKED ISSUE #147: fix master issues

### PR DESCRIPTION
**Pull request by odedre**
closed #147

### CODE REVIEW

File: community/ui/community-highlighter/community-highlighter.tsx [hunk 1]
```diff
@@ -10,14 +10,14 @@ export type CommunityHighlighterProps = {
...
-  const [disabled, setDisabled] = useState();
+  // const [disabled, setDisabled] = useState();
 
   return (
     <ComponentHighlighter
       classes={{ label: styles.label, frame: styles.frame }}
       placement="top"
       style={{ border: 'none' }}
-      disabled={disabled}
+      disabled
```
Comment (KutnerUri) [inline community/ui/community-highlighter/community-highlighter.tsx:20]: check this

File: community/ui/mocks/bit-dev/bit-dev.tsx [hunk 2]
```diff
@@ -19,7 +19,7 @@ export const BitDevMock = ({ component }: BitDevMockProps) => {
     <>
       <Header />
       <WideColumn>
-        <Docs baseUrl="" routes={routes} />
+        <Docs baseUrl="" contents={[{ routes }]} />
```
Comment (KutnerUri) [inline community/ui/mocks/bit-dev/bit-dev.tsx:22]: bad for perf - extract this array to a constant / memo

File: docs/plugins/docs/table-of-contents/table-of-contents.docs.mdx [hunk 3]
```diff
@@ -1,4 +1,4 @@
----
+<!-- ---
```
Comment (KutnerUri) [inline docs/plugins/docs/table-of-contents/table-of-contents.docs.mdx:1]: please delete

File: docs/ui/docs/docs.composition.tsx [hunk 4]
```diff
@@ -53,7 +53,7 @@ const routes: DocsRoute[] = [
 export const BasicDocs = () => (
   <Docs
     baseUrl="https://teambit-community-apps-bit-dev.netlify.app/docs"
-    routes={routes}
+    contents={[{ routes }]}
```
Comment (KutnerUri) [inline docs/ui/docs/docs.composition.tsx:56]: same - perf. extract to a constant

File: docs/ui/pages/doc-page/doc-page.composition.tsx [hunk 5]
```diff
@@ -1,9 +1,9 @@
-import React from 'react';
-import { DocPage } from './doc-page';
-import { CreateWorkspace } from '@teambit/docs.content.getting-started.create-workspace';
+// import React from 'react';
+// import { CreateWorkspace } from '@teambit/docs.content.getting-started.create-workspace';
+// import { DocPage } from './doc-page';
```
Comment (KutnerUri) [inline docs/ui/pages/doc-page/doc-page.composition.tsx:3]: check if this should be commented out

File: docs/ui/pages/doc-page/doc-page.specx.tsx [hunk 6]
```diff
@@ -1,9 +1,9 @@
-import React from 'react';
-import { render } from '@testing-library/react';
-import { BasicDocPage } from './doc-page.composition';
+// import React from 'react';
```
Comment (KutnerUri) [inline docs/ui/pages/doc-page/doc-page.specx.tsx:1]: please delete

**Review by KutnerUri — APPROVED** [review]
